package com.ntier.provided;

public class User {
	private String username; // read-only
	private String password;
	private String email;
	private boolean admin;

	public User(String username) {
		this.username = username;
	}

	public User(String username, String password, String email) {
		this(username);
		this.setPassword(password);
		this.setEmail(email);
	}

	public User(String username, String password, String email, boolean admin) {
		this(username, password, email);
		this.setAdmin(admin);
	}

	public String getUsername() {
		return username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isAdmin() {
		return admin;
	}

	public void setAdmin(boolean admin) {
		this.admin = admin;
	}

	public boolean equals(Object obj) {
		boolean result = false;
		if (obj instanceof User) {
			User other = (User) obj;
			result = this.getUsername().equals(other.getUsername());
		}
		return result;
	}

	/*
	 * Generated by RSA.
	 */
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = PRIME * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}

	public String toString() {
		return this.getClass().getName() + ":" + " username=" + this.getUsername() + " password=" + this.getPassword()
				+ " email=" + this.getEmail() + " admin=" + this.isAdmin();
	}
}